AWSTemplateFormatVersion: 2010-09-09

Description: Battleship

Resources:

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          exports.handler = function(event, context) {
            console.log(event);
            console.log(context);
          }
      Handler: index.handler
      Role: !GetAtt Role.Arn
      Runtime: nodejs8.10
      Timeout: 5
      MemorySize: 64

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
