version: 0.2
phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - rm -rf node_modules
      - npm install --production
artifacts:
  files:
    - '*.js'
    - 'components/*.js'
    - 'node_modules/**/*'
    - 'static/*.png'
