AWSTemplateFormatVersion: 2010-09-09

Description: Battleship

Transform: AWS::Serverless-2016-10-31

Parameters:

  Bucket:
    Type: String
    Description: S3 bucket name containing code for Lambda function

  Key:
    Type: String
    Description: S3 object key containing code for Lambda function

Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - '*~1*'
      EndpointConfiguration: REGIONAL
      StageName: Prod

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - battleship.dylanscott.com.au
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          ForwardedValues:
            QueryString: true
          TargetOriginId: Battleship
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
            Id: Battleship
            OriginPath: /Prod
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:584259415401:certificate/a71b279e-eadf-4440-b2fa-78e91d8b7608
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only


  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: Battleship
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        Home:
          Type: Api
          Properties:
            Method: GET
            Path: /
            RestApiId: !Ref Api
        Match:
          Type: Api
          Properties:
            Method: GET
            Path: /match
            RestApiId: !Ref Api
        Static:
          Type: Api
          Properties:
            Method: GET
            Path: /static/miss
            RestApiId: !Ref Api
        Upload:
          Type: Api
          Properties:
            Method: POST
            Path: /upload
            RestApiId: !Ref Api
      Handler: lambda.handler
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Ref Key
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      MemorySize: 128
      Runtime: nodejs8.10
      Timeout: 60

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String

Outputs:

  Battleship:
    Description: Battleship
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod
