AWSTemplateFormatVersion: 2010-09-09

Description: Battleship deployment pipeline

Parameters:

  OAuthToken:
    Type: String
    Description: GitHub OAuth token
    NoEcho: true

  SecretToken:
    Type: String
    Description: GitHub Webhook token
    NoEcho: true

Resources:

  Bucket:
    Type: AWS::S3::Bucket

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - iam:AttachRolePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:DetachRolePolicy
                  - iam:GetRole
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                Resource: '*'
            Version: 2012-10-17
          PolicyName: CloudFormation

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref Bucket
        Type: S3
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: dylanjgscott
                Repo: battleship
                PollForSourceChanges: false
                Branch: master
                OAuthToken: !Ref OAuthToken
              Name: Source
              OutputArtifacts:
                - Name: battleship
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                RoleArn: !GetAtt CloudFormationRole.Arn
                StackName: battleship
                TemplatePath: battleship::battleship.yml
              InputArtifacts:
                - Name: battleship
              Name: Deploy
          Name: Deploy

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DescribeStacks
                Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/battleship/*
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt CloudFormationRole.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub ${Bucket.Arn}/*
            Version: 2012-10-17
          PolicyName: Pipeline

  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
        Authentication: GITHUB_HMAC
        AuthenticationConfiguration:
          SecretToken: !Ref SecretToken
        Filters:
          - JsonPath: ref
            MatchEquals: refs/heads/master
        RegisterWithThirdParty: true
        TargetAction: Source
        TargetPipeline: !Ref Pipeline
        TargetPipelineVersion: !GetAtt Pipeline.Version
