AWSTemplateFormatVersion: 2010-09-09

Description: Battleship deployment pipeline

Parameters:

  OAuthToken:
    Type: String
    Description: GitHub OAuth token
    NoEcho: true

  SecretToken:
    Type: String
    Description: GitHub Webhook token
    NoEcho: true

Resources:

  Bucket:
    Type: AWS::S3::Bucket

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Action:
                  - s3:GetObject
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub ${Bucket.Arn}/*
            Version: 2012-10-17
          PolicyName: CodeBuild

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - apigateway:DELETE
                  - apigateway:GET
                  - apigateway:PATCH
                  - apigateway:POST
                  - apigateway:PUT
                  - cloudformation:CreateChangeSet
                  - cloudfront:CreateCloudFrontOriginAccessIdentity
                  - cloudfront:CreateDistribution
                  - cloudfront:DeleteCloudFrontOriginAccessIdentity
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetCloudFrontOriginAccessIdentity
                  - cloudfront:GetCloudFrontOriginAccessIdentityConfig
                  - cloudfront:GetDistribution
                  - cloudfront:TagResource
                  - cloudfront:UnTagResource
                  - cloudfront:UpdateDistribution
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - iam:AttachRolePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:GetRole
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - lambda:AddPermission
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:ListTags
                  - lambda:RemovePermission
                  - lambda:TagResource
                  - lambda:UntagResource
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:DeleteBucketPolicy
                  - s3:DeleteBucketWebsite
                  - s3:PutBucketPolicy
                  - s3:PutBucketWebsite
                Effect: Allow
                Resource: '*'
              - Action: s3:GetObject
                Effect: Allow
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub ${Bucket.Arn}/*
            Version: 2012-10-17
          PolicyName: CloudFormation

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref Bucket
        Type: S3
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: dylanjgscott
                Repo: battleship
                PollForSourceChanges: false
                Branch: master
                OAuthToken: !Ref OAuthToken
              OutputArtifacts:
                - Name: Source
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref Project
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: Build
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM
                ParameterOverrides: |
                  {
                    "CodeUriBucket": {
                      "Fn::GetArtifactAtt": [
                        "Build",
                        "BucketName"
                      ]
                    },
                    "CodeUriKey": {
                      "Fn::GetArtifactAtt": [
                        "Build",
                        "ObjectKey"
                      ]
                    }
                  }
                RoleArn: !GetAtt CloudFormationRole.Arn
                StackName: battleship
                TemplatePath: Build::cloudformation.yml
              InputArtifacts:
                - Name: Build

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Effect: Allow
                Resource: !GetAtt Project.Arn
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                Effect: Allow
                Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/battleship/*
              - Action: iam:PassRole
                Effect: Allow
                Resource: !GetAtt CloudFormationRole.Arn
              - Action:
                  - s3:GetObject
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub ${Bucket.Arn}/*
            Version: 2012-10-17
          PolicyName: Pipeline

  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: Battleship
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: node:8.10
        ImagePullCredentialsType: CODEBUILD
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE

  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
        Authentication: GITHUB_HMAC
        AuthenticationConfiguration:
          SecretToken: !Ref SecretToken
        Filters:
          - JsonPath: ref
            MatchEquals: refs/heads/master
        RegisterWithThirdParty: true
        TargetAction: Source
        TargetPipeline: !Ref Pipeline
        TargetPipelineVersion: !GetAtt Pipeline.Version
